<div class="heading" style="margin-bottom: 12px;">
                <div class="had_txt">Featured Range Hoods</div>
            </div>            
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('Featured-Range-Hoods')->toHtml() ?> 
            
               
                <div class="clear"></div>
                 
		<div class="heading homeonsale"  >
                <div class="had_txt">On Sale</div>
            </div> 
            
              <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('On-Sale')->toHtml() ?>      
              
                <div class="clear"></div>
  